name: Pull Request CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-latest-aurora-run-community-tests:
    name: 'Run Community Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 8
      - name: 'Run Community Tests'
        run: |
          ./gradlew --no-parallel --no-daemon test-community-docker
      - name: 'Archive junit results'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'junit-report'
          path: build/reports/tests/
          retention-days: 5
