name: Mark and Close Stale Issues

on:
  schedule:
    # Every Monday at 01:00 UTC
    - cron: '0 1 * * 1'

jobs:
  stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Mark Issues as Stale and Close Stale Issues
        uses: actions/stale@v5.0.0
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          days-before-pr-stale: -1
          days-before-pr-close: -1
          stale-pr-message: 'This issues has been marked as stale because it received no updates in the past 30 days. It will be closed in 14 days if no further activity occurs.'
